---
- name: Playbook 2.9
  hosts: web2
  become: true
  tasks:
    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present
        update_cache: true

    - name: Install dnsutils
      ansible.builtin.dnf:
        name: dnsutils
        state: present
        update_cache: true
