---
- name: Playbook 5.1
  hosts: ubuntu
  become: true
  tasks:
    - name: Copy /etc/ansible/hosts
      ansible.builtin.copy:
        src: /etc/ansible/hosts
        dest: /home/super/ansible-hosts.txt
