---
- name: Playbook 4.4
  hosts: data
  become: true
  tasks:
    - name: Check if the file exists
      ansible.builtin.stat:
        path: /mysql_update
      register: result
      
    - name: Update mysql
      ansible.builtin.dnf:
        name: mysql
        state: latest
      when: result.stat.exists
